import "./globals.css";

import DefaultValues from "@/components/Default-Values/DeafaultValues";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <StoreProvider>
            <Header />
            <DefaultValues />
            {children}
            <Footer />
          </StoreProvider>
        </main>
      </body>
    </html>
  );
}
